server:
  port: 8002
spring:
  application:
    name: order-nacos
  cloud:
    nacos:
      server-addr: http://8.134.144.240:8848
      discovery:
        username: nacos
        password: nacos
        namespace: 66303517-4bae-4f16-9874-1466561154b2
        group: test