server:
  port: 8014

spring:
  application:
    name: nacosConfig
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.144.240:8848
        namespace: 66303517-4bae-4f16-9874-1466561154b2
        group: test
      username: nacos
      password: nacos
      config:
        server-addr: 8.134.144.240:8848
        file-extension: properties
        namespace: 66303517-4bae-4f16-9874-1466561154b2
        group: test
        prefix: nacosConfig
  config:
    import:
      - optional:nacos:nacosConfig-dev.properties
  profiles:
    active: dev
